
stages:        
  - build
  - lint_format
  - migrations
  - tests
  - deploy

build-job:      
  stage: build
  before_script:
    - cp ${ENV} .env
    - cp ${TEST_ENV} .env-test
  script:
    - docker build -t booking-api-image .

Lint:
  stage: lint_format
  script:
     - docker run --rm --network my_network booking-api-image ruff check

Format:
  stage: lint_format
  script:
     - docker run --rm --network my_network booking-api-image ruff format --check

Migrations:
  stage: migrations
  script: 
      docker run --rm --env-file .env --network my_network booking-api-image alembic upgrade head

Tests:
  stage: tests
  script:
      - docker run --rm --env-file .env-test --network my_network booking-api-image pytest -s -v
deploy-job:    
  stage: deploy 
  script:
    - docker compose -f docker-compose-ci.yml up -d
    - docker exec booking_nginx nginx -s reload
