services:
  booking_back_service:
    container_name: "booking_back"
    build:
      context: .
    # ports:
    #   - "7777:8000"
    networks:
      - my_network
    env_file:
      - .env

  celery_worker_service:
    container_name: "celery_worker"
    build:
      context: .
    networks:
      - my_network
    env_file:
      - .env
    command: "celery -A src.tasks.celery_app:celery_instance worker -l INFO"

  celery_beat_service:
    container_name: "celery_beat"
    build:
      context: .
    networks:
      - my_network
    env_file:
      - .env
    command: "celery -A src.tasks.celery_app:celery_instance beat -l INFO"

  booking_cache_service:
    container_name: "booking_cache"
    image: redis:7.4
    ports:
      - "7379:6379"
    networks:
      - my_network

networks:
  my_network:
    external: true